### ISSUE TITLE
集成FOSUserBundle

### ISSUE THREAD

**Issue by xsilen** [meipet/meipet_backend#6]
**我正在...**  (用 "x" 来选择)
```
[x] 任务
[ ] 提交BUG
[ ] 新功能需求
[ ] 设计文档
```

预计用时4h
deadline 2017/03/11

任务:

 - [x] 先使用User类继承FOS\UserBundle\Model\User来测试
 - [x] 参考ultimate-symfony2-boilerplate
 - [x] hard to understand FOSUserBundle
 - [x] 检查ROLE是否可以有层级. 是的,有层级
 - [x] 开始测试
 - [ ] 测试完毕 
 - [ ] 集成FOSUserBundle成功

引用
ref:  https://github.com/FriendsOfSymfony/FOSUserBundle
ref: https://symfony.com/doc/master/bundles/FOSUserBundle/index.html

结果
![image](https://cloud.githubusercontent.com/assets/5467712/23751482/89dfcf22-050c-11e7-8301-57a2c1b722df.png)

**Comment by xsilen** [comment]
ultimate-symfony2-boilerplate 配置FOSUserBundle如下:
config.yml
```yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: app_user_registration
```
